# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mineral_cost', models.IntegerField()),
                ('gas_cost', models.IntegerField()),
                ('supply_cost', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('attack_range', models.IntegerField()),
                ('cooldown', models.DecimalField(decimal_places=2, max_digits=10)),
                ('speed', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
    ]
